function(detect_libcpp)
    set(OLD_CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
    set(TEST_FILE "${CMAKE_BINARY_DIR}/test_stdlib.cpp")
    file(WRITE "${TEST_FILE}" "#include <vector>\nint main() {}\n")
    try_compile(HAS_LIBCPP "${CMAKE_BINARY_DIR}" "${TEST_FILE}")
    set(HAS_LIBCPP "${HAS_LIBCPP}" PARENT_SCOPE)
    set(CMAKE_CXX_FLAGS ${OLD_CMAKE_CXX_FLAGS})
    unset(OLD_CMAKE_CXX_FLAGS)
endfunction()
